#!/usr/bin/env python3
"""Generate the installer's association entries from Kainote/FileTypes.h.

The table there is the single source of truth for the 18 file types: the
extension, the icon resource id, and whether it is a subtitle or a video. The
installer has to agree with what Registry.cpp writes at runtime, so it is
generated rather than hand-maintained.
"""

import argparse
import pathlib
import re
import sys

ROW = re.compile(
    r'\{\s*L"(?P<ext>\.[a-z0-9]+)"\s*,\s*'
    r'(?P<icon>IDI_FILETYPE_[A-Z0-9]+)\s*,\s*'
    r'(?:nullptr|"[^"]*")\s*,\s*'
    r'wxTRANSLATE\(L"(?P<desc>[^"]*)"\)\s*,\s*'
    r'KainoteFileKind::(?P<kind>\w+)',
    re.S)

TASK_FOR_KIND = {"Subtitle": "assoc_subs", "Video": "assoc_video"}


def read_table(repo: pathlib.Path):
    header = (repo / "Kainote" / "FileTypes.h").read_text(encoding="utf-8")
    ids = {m.group(1): int(m.group(2)) for m in
           re.finditer(r"#define\s+(IDI_\w+)\s+(\d+)",
                       (repo / "Kainote" / "FileTypeIcons.h").read_text(encoding="utf-8"))}

    rows = []
    for m in ROW.finditer(header):
        ext = m.group("ext")
        rows.append({
            "ext": ext,
            "icon": ids[m.group("icon")],
            "desc": m.group("desc"),
            # .txt is text/plain in all but name. A machine-wide handler for it
            # is aggressive enough to deserve its own opt-in.
            "task": "assoc_txt" if ext == ".txt" else TASK_FOR_KIND[m.group("kind")],
        })
    return rows


def emit(rows, prog_id_prefix):
    out = [
        "; Generated by packaging/windows/gen_associations.py -- do not edit.",
        "; Source of truth: Kainote/FileTypes.h + Kainote/FileTypeIcons.h",
        "",
        "[Registry]",
    ]
    for r in rows:
        prog = f"{prog_id_prefix}{r['ext']}"
        out += [
            f"; {r['ext']}  ({r['desc']})",
            f'Root: HKLM; Subkey: "Software\\Classes\\{prog}"; ValueType: string; '
            f'ValueData: "{r["desc"]}"; Flags: uninsdeletekey',
            f'Root: HKLM; Subkey: "Software\\Classes\\{prog}\\DefaultIcon"; ValueType: string; '
            f'ValueData: """{{app}}\\Kainote.exe"",-{r["icon"]}"',
            f'Root: HKLM; Subkey: "Software\\Classes\\{prog}\\Shell\\Open\\Command"; ValueType: string; '
            f'ValueData: """{{app}}\\Kainote.exe"" ""%1"""',
            # Always offered under "Open with"; only the default is opt-in.
            f'Root: HKLM; Subkey: "Software\\Classes\\{r["ext"]}\\OpenWithProgIds"; ValueType: string; '
            f'ValueName: "{prog}"; ValueData: ""; Flags: uninsdeletevalue',
            f'Root: HKLM; Subkey: "Software\\Classes\\{r["ext"]}"; ValueType: string; '
            f'ValueData: "{prog}"; Flags: uninsdeletevalue; Tasks: {r["task"]}',
            f'Root: HKLM; Subkey: "Software\\Kainote\\Capabilities\\FileAssociations"; ValueType: string; '
            f'ValueName: "{r["ext"]}"; ValueData: "{prog}"',
            f'Root: HKLM; Subkey: "Software\\Classes\\Applications\\Kainote.exe\\SupportedTypes"; '
            f'ValueType: string; ValueName: "{r["ext"]}"; ValueData: ""',
            # The app writes its own HKCU entries. dontcreatekey means we never
            # create them, only remove them when uninstalling.
            f'Root: HKCU; Subkey: "Software\\Classes\\{prog}"; '
            f'Flags: dontcreatekey uninsdeletekey',
            "",
        ]
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", default=pathlib.Path(__file__).resolve().parents[2])
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    repo = pathlib.Path(args.repo)
    rows = read_table(repo)
    if len(rows) != 18:
        sys.exit(f"expected 18 file types in FileTypes.h, parsed {len(rows)}")

    icons = [r["icon"] for r in rows]
    if icons != list(range(icons[0], icons[0] + len(icons))):
        sys.exit(f"icon ids are not contiguous: {icons}")

    pathlib.Path(args.out).write_text(emit(rows, "Kainote"), encoding="utf-8")
    print(f"{args.out}: {len(rows)} file types, icon ids {icons[0]}..{icons[-1]}")


if __name__ == "__main__":
    main()
